# Write conf/nginx.conf from the app's settings. Server blocks of your own go
# in conf/sites/*.conf, which XDeck never touches.
. (Join-Path $PSScriptRoot 'lib.ps1')
$state = Get-State

$bind = if ($env:BIND) { $env:BIND } else { '0.0.0.0' }
$port = if ($env:PORT) { $env:PORT } else { '8080' }
foreach ($d in 'conf\sites', 'temp', 'logs') {
    New-Item -ItemType Directory -Force -Path (Join-Path $AppDir $d) | Out-Null
}

Write-TextFile (Join-Path $AppDir 'conf\nginx.conf') @"
# Generated by XDeck from the app's settings; changes here are overwritten.
# Add your own server blocks in conf/sites/*.conf.
worker_processes 1;
pid logs/nginx.pid;
error_log stderr warn;

events {
    worker_connections 1024;
}

http {
    include mime.types;
    default_type application/octet-stream;
    access_log logs/access.log;
    sendfile on;
    keepalive_timeout 65;

    client_body_temp_path temp/client_body;
    proxy_temp_path temp/proxy;
    fastcgi_temp_path temp/fastcgi;
    uwsgi_temp_path temp/uwsgi;
    scgi_temp_path temp/scgi;

    server {
        listen ${bind}:${port};
        server_name _;
        root html;
        index index.html;

        location / {
            try_files `$uri `$uri/ =404;
        }
    }

    include sites/*.conf;
}
"@

$prefix = (ConvertTo-SlashPath $AppDir) + '/'
Invoke-Native $state.exe @('-p', $prefix, '-c', 'conf/nginx.conf', '-e', 'stderr', '-t')
