#!/usr/bin/env bash
# Write conf/nginx.conf from the app's settings. Server blocks of your own go
# in conf/sites/*.conf, which XDeck never touches.
. "$(dirname "$0")/lib.sh"
state_load

mkdir -p "$APP_DIR/conf/sites" "$APP_DIR/temp" "$APP_DIR/run"
user=""
# Workers of a root master would run as nobody; keep them able to read html/.
is_root && user="user root;"

write_file "$APP_DIR/conf/nginx.conf" <<CONF
# Generated by XDeck from the app's settings; changes here are overwritten.
# Add your own server blocks in conf/sites/*.conf.
$user
worker_processes auto;
pid run/nginx.pid;
error_log stderr warn;

events {
    worker_connections 1024;
}

http {
    include mime.types;
    default_type application/octet-stream;
    access_log /dev/stdout;
    sendfile on;
    keepalive_timeout 65;

    client_body_temp_path temp/client_body;
    proxy_temp_path temp/proxy;
    fastcgi_temp_path temp/fastcgi;
    uwsgi_temp_path temp/uwsgi;
    scgi_temp_path temp/scgi;

    server {
        listen ${BIND:-0.0.0.0}:${PORT:-8080};
        server_name _;
        root html;
        index index.html;

        location / {
            try_files \$uri \$uri/ =404;
        }
    }

    include sites/*.conf;
}
CONF

flags=(-p "$APP_DIR/" -c conf/nginx.conf)
[ "$NGINX_ERROR_LOG_FLAG" = 1 ] && flags+=(-e stderr)
"$NGINX_BIN" "${flags[@]}" -t
