services:
  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?a password is required}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    ports:
      - ${BIND:-127.0.0.1}:${PORT:-5432}:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    shm_size: 128mb
    healthcheck:
      test: [CMD-SHELL, 'pg_isready -U "$$POSTGRES_USER" -d "$$POSTGRES_DB"']
      interval: 10s
      timeout: 5s
      retries: 5
