#!/usr/bin/env bash
# Write data/xdeck.conf (address, port, socket) and the remote access rules
# of pg_hba.conf from the app's settings.
. "$(dirname "$0")/lib.sh"
. "$(dirname "$0")/postgres.sh"
state_load

[ -f "$DATA_DIR/postgresql.conf" ] || die "data/ has no cluster; reinstall the app"
listen="${BIND:-127.0.0.1}"
[ "$listen" = 0.0.0.0 ] && listen="*"

write_file "$DATA_DIR/xdeck.conf" <<CONF
# Generated by XDeck from the app's settings; changes here are overwritten.
listen_addresses = '$listen'
port = ${PORT:-5432}
unix_socket_directories = '$RUN_DIR'
CONF

if ! grep -q "^include_if_exists = 'xdeck.conf'" "$DATA_DIR/postgresql.conf"; then
  printf "\n# Settings managed by XDeck\ninclude_if_exists = 'xdeck.conf'\n" >>"$DATA_DIR/postgresql.conf"
fi

# Remote connections need a rule besides the local ones initdb wrote.
hba="$DATA_DIR/pg_hba.conf"
sed '/^# BEGIN XDeck/,/^# END XDeck/d' "$hba" >"$hba.tmp"
if [ "${BIND:-127.0.0.1}" = 0.0.0.0 ]; then
  cat >>"$hba.tmp" <<HBA
# BEGIN XDeck: remote access (listen address: all interfaces)
host all all 0.0.0.0/0 scram-sha-256
host all all ::/0 scram-sha-256
# END XDeck
HBA
fi
mv "$hba.tmp" "$hba"
chmod 600 "$DATA_DIR/xdeck.conf" "$hba"
mkdir -p "$RUN_DIR"
own "$DATA_DIR/xdeck.conf" "$hba" "$RUN_DIR"
log "Wrote data/xdeck.conf"
