# MongoDB helpers shared by this app's scripts (after lib.sh).

MONGO_VERSION=8.0.32
MONGOSH_VERSION=2.13.0
DIST_DIR="$APP_DIR/mongodb"
SHELL_DIR="$APP_DIR/mongosh"
DATA_DIR="$APP_DIR/data"
RUN_DIR="$APP_DIR/run"
CONF="$APP_DIR/conf/mongod.conf"

# Pinned SHA-256 of a download, from checksums.txt.
pinned_sha256() {
  awk -v f="$1" '$2 == f {print $1}' "$(dirname "${BASH_SOURCE[0]}")/checksums.txt"
}

# The official build for this Linux distribution, e.g. ubuntu2404.
linux_target() {
  local id like version major
  id="$(os_release ID)"
  like="$(os_release ID_LIKE)"
  version="$(os_release VERSION_ID)"
  major="${version%%.*}"
  case "$id" in
    ubuntu)
      case "$major" in
        20) echo ubuntu2004 ;;
        22) echo ubuntu2204 ;;
        2[4-9] | [3-9][0-9]) echo ubuntu2404 ;;
      esac
      ;;
    debian) [ "${major:-0}" -ge 12 ] 2>/dev/null && echo debian12 ;;
    amzn)
      case "$major" in
        2023) echo amazon2023 ;;
        2) echo amazon2 ;;
      esac
      ;;
    fedora) echo rhel93 ;;
    sles | opensuse-leap) [ "$major" = 15 ] && echo suse15 ;;
    *)
      case " $like " in
        *" rhel "* | *" centos "* | *" fedora "*)
          case "$major" in
            8) echo rhel8 ;;
            9) echo rhel93 ;;
            1[0-9]) echo rhel10 ;;
          esac
          ;;
        *" ubuntu "*) echo ubuntu2404 ;;
      esac
      ;;
  esac
  true
}

# Write conf/mongod.conf from the settings.
write_conf() {
  mkdir -p "$APP_DIR/conf" "$RUN_DIR"
  write_file "$CONF" <<CONF
# Generated by XDeck from the app's settings; changes here are overwritten.
storage:
  dbPath: "$DATA_DIR"
net:
  port: ${PORT:-27017}
  bindIp: "${BIND:-127.0.0.1}"
  unixDomainSocket:
    pathPrefix: "$RUN_DIR"
security:
  authorization: enabled
CONF
}
