# MongoDB helpers shared by this app's Windows scripts (after lib.ps1).

$MongoVersion = '8.0.32'
$MongoshVersion = '2.13.0'
$DistDir = Join-Path $AppDir 'mongodb'
$ShellDir = Join-Path $AppDir 'mongosh'
$DataDir = Join-Path $AppDir 'data'
$Conf = Join-Path $AppDir 'conf\mongod.conf'
$Mongod = Join-Path $DistDir 'bin\mongod.exe'

# Pinned SHA-256 of a download, from checksums.txt.
function Get-PinnedSha256([string]$File) {
    foreach ($line in Get-Content (Join-Path $PSScriptRoot 'checksums.txt')) {
        $parts = $line -split '\s+'
        if ($parts.Count -ge 2 -and $parts[1] -eq $File) { return $parts[0] }
    }
    Stop-WithError "no checksum for $File"
}

# Write conf/mongod.conf from the settings.
function Write-Conf {
    $port = if ($env:PORT) { $env:PORT } else { '27017' }
    $bind = if ($env:BIND) { $env:BIND } else { '127.0.0.1' }
    Write-TextFile $Conf @"
# Generated by XDeck from the app's settings; changes here are overwritten.
storage:
  dbPath: "$(ConvertTo-SlashPath $DataDir)"
net:
  port: $port
  bindIp: "$bind"
security:
  authorization: enabled
"@
}
