# MySQL helpers shared by this app's Windows scripts (after lib.ps1).

$MysqlVersion = '8.4.11'
$MysqlSha256 = 'a492371d687d2bab088b0062581144a0044b8964baefdf4faa579292b423d25c'
$DistDir = Join-Path $AppDir 'mysql'
$DataDir = Join-Path $AppDir 'data'
$Cnf = Join-Path $AppDir 'conf\my.ini'
$Mysqld = Join-Path $DistDir 'bin\mysqld.exe'

# Write conf/my.ini from the settings. Extra options go in conf/conf.d/*.cnf.
function Write-Cnf {
    $port = if ($env:PORT) { $env:PORT } else { '3306' }
    $bind = if ($env:BIND) { $env:BIND } else { '127.0.0.1' }
    foreach ($d in 'conf\conf.d', 'files') {
        New-Item -ItemType Directory -Force -Path (Join-Path $AppDir $d) | Out-Null
    }
    $s = { param($p) ConvertTo-SlashPath $p }
    Write-TextFile $Cnf @"
# Generated by XDeck from the app's settings; changes here are overwritten.
# Add your own options in conf/conf.d/*.cnf.
[mysqld]
basedir = $(& $s $DistDir)
datadir = $(& $s $DataDir)
port = $port
bind-address = $bind
secure-file-priv = $(& $s (Join-Path $AppDir 'files'))
mysqlx = OFF

[client]
port = $port

!includedir $(& $s (Join-Path $AppDir 'conf\conf.d'))
"@
}

function ConvertTo-SqlString([string]$Value) {
    "'" + ($Value -replace '\\', '\\' -replace "'", "\'") + "'"
}

function ConvertTo-SqlIdent([string]$Value) {
    '`' + ($Value -replace '`', '``') + '`'
}
