# MySQL helpers shared by this app's scripts (after lib.sh).

MYSQL_VERSION=8.4.11
DIST_DIR="$APP_DIR/mysql"
DATA_DIR="$APP_DIR/data"
RUN_DIR="$APP_DIR/run"
CNF="$APP_DIR/conf/my.cnf"

# Write conf/my.cnf from the settings. Extra options go in conf/conf.d/*.cnf.
write_cnf() {
  mkdir -p "$APP_DIR/conf/conf.d" "$RUN_DIR" "$APP_DIR/files"
  {
    echo "# Generated by XDeck from the app's settings; changes here are overwritten."
    echo "# Add your own options in conf/conf.d/*.cnf."
    echo "[mysqld]"
    echo "basedir = $DIST_DIR"
    echo "datadir = $DATA_DIR"
    echo "port = ${PORT:-3306}"
    echo "bind-address = ${BIND:-127.0.0.1}"
    echo "socket = $RUN_DIR/mysqld.sock"
    echo "pid-file = $RUN_DIR/mysqld.pid"
    echo "secure-file-priv = $APP_DIR/files"
    echo "mysqlx = OFF"
    # mysqld only runs as root when told so explicitly.
    if is_root; then echo "user = root"; fi
    echo
    echo "[client]"
    echo "socket = $RUN_DIR/mysqld.sock"
    echo "port = ${PORT:-3306}"
    echo
    echo "!includedir $APP_DIR/conf/conf.d"
  } | write_file "$CNF"
}

use_libs() {
  if [ -n "${MYSQL_LIB_DIR:-}" ]; then
    export LD_LIBRARY_PATH="$MYSQL_LIB_DIR${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
  fi
}

# Quote a MySQL identifier.
sql_ident() {
  printf '`%s`' "${1//\`/\`\`}"
}
